/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.60
 * Generated at: 2023-01-02 00:37:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/D:/PJW/pro07_1/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/pro07/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/PJW/pro07_1/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/pro07/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1668994676356L));
    _jspx_dependants.put("jar:file:/D:/PJW/pro07_1/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/pro07/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, user-scalable=no\">\r\n");
      out.write("<title>회원가입</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("	<div data-role=\"content\" class=\"ui-content\">\r\n");
      out.write("       <form name=\"frm1\" id=\"frm1\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/insert.do\" method=\"post\" >\r\n");
      out.write("            <div class=\"field\">\r\n");
      out.write("                <label class=\"label\">아이디</label>\r\n");
      out.write("                <div class=\"control\">\r\n");
      out.write("                    <input class=\"input\" type=\"text\" placeholder=\"아이디를 입력하세요\" name=\"id\" id=\"id\">\r\n");
      out.write("                   \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"field\">\r\n");
      out.write("                <label class=\"label\">비밀번호</label>\r\n");
      out.write("                <div class=\"control\">\r\n");
      out.write("                    <input class=\"input\" type=\"password\" placeholder=\"비밀번호를 입력하세요\" name=\"pw\" id=\"pw\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("           \r\n");
      out.write("               <div class=\"field\">\r\n");
      out.write("                <label class=\"label\">이름</label>\r\n");
      out.write("                <div class=\"control\">\r\n");
      out.write("                    <input class=\"input\" type=\"text\" placeholder=\"이름\" name=\"name\" id=\"name\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"field\">\r\n");
      out.write("                <label class=\"label\">전화번호</label>\r\n");
      out.write("                <div class=\"control\">\r\n");
      out.write("                    <input class=\"input\" type=\"text\" placeholder=\"전화번호를 입력하세요\" name=\"tel\" id=\"tel\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"field\">\r\n");
      out.write("                <label class=\"label\">주소</label>\r\n");
      out.write("                <div class=\"control\">\r\n");
      out.write("                    <input class=\"input\" type=\"text\" name=\"addr\" id=\"addr\" placeholder=\"기본주소 입력\" maxlength=\"150\" required><br><br>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"buttons\">\r\n");
      out.write("                <button type=\"submit\" class=\"button is-primary is-light\">가입</button>\r\n");
      out.write("                <button type=\"reset\" class=\"button is-link is-light\">취소</button>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <script src=\"https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("      <div class=\"py-5 text-center\">\r\n");
      out.write("        <img class=\"d-block mx-auto mb-4\" src=\"https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg\" alt=\"\" width=\"72\" height=\"72\">\r\n");
      out.write("        <h2>Checkout form</h2>\r\n");
      out.write("        <p class=\"lead\">Below is an example form built entirely with Bootstrap's form controls. Each required form group has a validation state that can be triggered by attempting to submit the form without completing it.</p>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-md-4 order-md-2 mb-4\">\r\n");
      out.write("          <h4 class=\"d-flex justify-content-between align-items-center mb-3\">\r\n");
      out.write("            <span class=\"text-muted\">Your cart</span>\r\n");
      out.write("            <span class=\"badge badge-secondary badge-pill\">3</span>\r\n");
      out.write("          </h4>\r\n");
      out.write("       \r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-8 order-md-1\">\r\n");
      out.write("          <h4 class=\"mb-3\">회원가입</h4>\r\n");
      out.write("          <form name=\"frm1\" id=\"frm1\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/insert.do\" method=\"post\" >\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-md-6 mb-3\">\r\n");
      out.write("               <label class=\"label\">아이디</label>\r\n");
      out.write("                <div class=\"control\">\r\n");
      out.write("                    <input class=\"input\" type=\"text\" placeholder=\"아이디를 입력하세요\" name=\"id\" id=\"id\">\r\n");
      out.write("                   \r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("               <div class=\"field\">\r\n");
      out.write("                <label class=\"label\">이름</label>\r\n");
      out.write("                <div class=\"control\">\r\n");
      out.write("                    <input class=\"input\" type=\"text\" placeholder=\"이름\" name=\"name\" id=\"name\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("              <label for=\"username\">Username</label>\r\n");
      out.write("              <div class=\"input-group\">\r\n");
      out.write("                <div class=\"input-group-prepend\">\r\n");
      out.write("                  <span class=\"input-group-text\">@</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"username\" placeholder=\"Username\" required=\"\">\r\n");
      out.write("                <div class=\"invalid-feedback\" style=\"width: 100%;\">\r\n");
      out.write("                  Your username is required.\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("              <label for=\"email\">Email <span class=\"text-muted\">(Optional)</span></label>\r\n");
      out.write("              <input type=\"email\" class=\"form-control\" id=\"email\" placeholder=\"you@example.com\">\r\n");
      out.write("              <div class=\"invalid-feedback\">\r\n");
      out.write("                Please enter a valid email address for shipping updates.\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("              <label for=\"address\">Address</label>\r\n");
      out.write("              <input type=\"text\" class=\"form-control\" id=\"address\" placeholder=\"1234 Main St\" required=\"\">\r\n");
      out.write("              <div class=\"invalid-feedback\">\r\n");
      out.write("                Please enter your shipping address.\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("              <label for=\"address2\">Address 2 <span class=\"text-muted\">(Optional)</span></label>\r\n");
      out.write("              <input type=\"text\" class=\"form-control\" id=\"address2\" placeholder=\"Apartment or suite\">\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-md-5 mb-3\">\r\n");
      out.write("                <label for=\"country\">Country</label>\r\n");
      out.write("                <select class=\"custom-select d-block w-100\" id=\"country\" required=\"\">\r\n");
      out.write("                  <option value=\"\">Choose...</option>\r\n");
      out.write("                  <option>United States</option>\r\n");
      out.write("                </select>\r\n");
      out.write("                <div class=\"invalid-feedback\">\r\n");
      out.write("                  Please select a valid country.\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-md-4 mb-3\">\r\n");
      out.write("                <label for=\"state\">State</label>\r\n");
      out.write("                <select class=\"custom-select d-block w-100\" id=\"state\" required=\"\">\r\n");
      out.write("                  <option value=\"\">Choose...</option>\r\n");
      out.write("                  <option>California</option>\r\n");
      out.write("                </select>\r\n");
      out.write("                <div class=\"invalid-feedback\">\r\n");
      out.write("                  Please provide a valid state.\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-md-3 mb-3\">\r\n");
      out.write("                <label for=\"zip\">Zip</label>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"zip\" placeholder=\"\" required=\"\">\r\n");
      out.write("                <div class=\"invalid-feedback\">\r\n");
      out.write("                  Zip code required.\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <hr class=\"mb-4\">\r\n");
      out.write("            <div class=\"custom-control custom-checkbox\">\r\n");
      out.write("              <input type=\"checkbox\" class=\"custom-control-input\" id=\"same-address\">\r\n");
      out.write("              <label class=\"custom-control-label\" for=\"same-address\">Shipping address is the same as my billing address</label>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"custom-control custom-checkbox\">\r\n");
      out.write("              <input type=\"checkbox\" class=\"custom-control-input\" id=\"save-info\">\r\n");
      out.write("              <label class=\"custom-control-label\" for=\"save-info\">Save this information for next time</label>\r\n");
      out.write("            </div>\r\n");
      out.write("            <hr class=\"mb-4\">\r\n");
      out.write("\r\n");
      out.write("            <h4 class=\"mb-3\">Payment</h4>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"d-block my-3\">\r\n");
      out.write("              <div class=\"custom-control custom-radio\">\r\n");
      out.write("                <input id=\"credit\" name=\"paymentMethod\" type=\"radio\" class=\"custom-control-input\" checked=\"\" required=\"\">\r\n");
      out.write("                <label class=\"custom-control-label\" for=\"credit\">Credit card</label>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"custom-control custom-radio\">\r\n");
      out.write("                <input id=\"debit\" name=\"paymentMethod\" type=\"radio\" class=\"custom-control-input\" required=\"\">\r\n");
      out.write("                <label class=\"custom-control-label\" for=\"debit\">Debit card</label>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"custom-control custom-radio\">\r\n");
      out.write("                <input id=\"paypal\" name=\"paymentMethod\" type=\"radio\" class=\"custom-control-input\" required=\"\">\r\n");
      out.write("                <label class=\"custom-control-label\" for=\"paypal\">Paypal</label>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-md-6 mb-3\">\r\n");
      out.write("                <label for=\"cc-name\">Name on card</label>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"cc-name\" placeholder=\"\" required=\"\">\r\n");
      out.write("                <small class=\"text-muted\">Full name as displayed on card</small>\r\n");
      out.write("                <div class=\"invalid-feedback\">\r\n");
      out.write("                  Name on card is required\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-md-6 mb-3\">\r\n");
      out.write("                <label for=\"cc-number\">Credit card number</label>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"cc-number\" placeholder=\"\" required=\"\">\r\n");
      out.write("                <div class=\"invalid-feedback\">\r\n");
      out.write("                  Credit card number is required\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-md-3 mb-3\">\r\n");
      out.write("                <label for=\"cc-expiration\">Expiration</label>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"cc-expiration\" placeholder=\"\" required=\"\">\r\n");
      out.write("                <div class=\"invalid-feedback\">\r\n");
      out.write("                  Expiration date required\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-md-3 mb-3\">\r\n");
      out.write("                <label for=\"cc-expiration\">CVV</label>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"cc-cvv\" placeholder=\"\" required=\"\">\r\n");
      out.write("                <div class=\"invalid-feedback\">\r\n");
      out.write("                  Security code required\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <hr class=\"mb-4\">\r\n");
      out.write("            <button class=\"btn btn-primary btn-lg btn-block\" type=\"submit\">Continue to checkout</button>\r\n");
      out.write("          </form>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <footer class=\"my-5 pt-5 text-muted text-center text-small\">\r\n");
      out.write("        <p class=\"mb-1\">© 2017-2018 Company Name</p>\r\n");
      out.write("        <ul class=\"list-inline\">\r\n");
      out.write("          <li class=\"list-inline-item\"><a href=\"#\">Privacy</a></li>\r\n");
      out.write("          <li class=\"list-inline-item\"><a href=\"#\">Terms</a></li>\r\n");
      out.write("          <li class=\"list-inline-item\"><a href=\"#\">Support</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </footer>\r\n");
      out.write("    </div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/member/join.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path1");
      // /WEB-INF/views/member/join.jsp(6,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/member/join.jsp(6,0) '${pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
